### ISSUE TITLE
Only passes data to NetworkTables if both pieces of tape are seen

### ISSUE THREAD

**Issue by haydenshively** [Team4256/4256-17-Edison#1]
The code detects the tape regardless of whether it sees both pieces, but since it doesn't know which one it has seen, it doesn't pass gear peg data to NetworkTables unless both are seen. Could add code to make assumptions about where other tape is based on previous frames.

**Comment by dsjj4son** [comment]
Hayden what are you thinking as far as the algorithm?  If you look at the
values we send last night the current recognition code drops the second
rectangle at about 3 feet out so looking for both does not seem ideal.  Are
you able to retried the size of the rectangles in Python?
